### ISSUE TITLE
Error using google colab notebooks

### ISSUE THREAD

**Issue by gold-olar** [miracle5284/engpy#4]
![WhatsApp Image 2020-11-09 at 11 32 36 AM](https://user-images.githubusercontent.com/43508719/99829244-58b25580-2b5c-11eb-9a0b-de535dd0b939.jpeg)

module 'engpy' has no attribute 'tools'  is the error I get when i try to use this package... @miracle5284 please address this...

**Comment by miracle5284** [comment]
Oh, sorry about that. will work on it and try to resolve it as soon as possible.

**Comment by miracle5284** [comment]
The Issue has been addressed and resolved. Thanks @gold-olar
